version: "3.7"

services:
  backend:
    container_name: catraca_stock
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=3000
      - TZ=America/Sao_Paulo
    volumes:
      - ./src:/var/www/catraca_stock/src
      - ./test:/var/www/catraca_stock/test
    working_dir: /var/www/catraca_stock
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: catraca_stock_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=catraca
      - MYSQL_PASSWORD=catraca
      - MYSQL_DATABASE=catraca_stock
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - catraca_stock_mysql_data:/var/lib/mysql

    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=America/Sao_Paulo']

volumes:
  catraca_stock_mysql_data:

networks:
  default:
      name: catraca
